#!/bin/bash
configfile=$1
if [ -z "$configfile" ]; then
	configfile=/etc/shutdownd.conf
fi
if [ -f "$configfile" ]; then
	source $configfile
else
	echo "This script expects a config file as parameter"
	exit 1
fi

if [ -z "$FILE" ] && [ -z "$IPRANGE" ] && [ -z "$USER_IDLE" ]; then
	exit 1
fi

if [ -n "$FILE" ]; then
	touch $FILE
	chmod 666 $FILE --quiet
fi

if [ -z "$SHUTDOWN_CMD" ]; then
	SHUTDOWN_CMD="shutdown -h now"
fi

last_skip_log_time=0
do_shutdown() {
	local flag=1
	if [ -f "$SKIP_FILE" ]; then
		local skip=`cat "$SKIP_FILE"`
		if [ -n "$skip" -a `date +%s` -lt $skip ]; then
			flag=0
			if [ "$last_skip_log_time" -ne "$skip" ]; then
				last_skip_log_time=$skip
				local log_tmp="skip shutdown until `date --rfc-3339=seconds -d @${skip}`"
				if [ -n "$LOGFILE" ]; then
					echo "[`date -R`] ${log_tmp}" >> "$LOGFILE"
				else
					logger "${log_tmp}"
				fi
			fi
		fi
	fi

	if [ $flag -eq 1 ]; then
		local log_tmp="performing shutdown (${SHUTDOWN_CMD})"
		if [ -n "$LOGFILE" ]; then
			echo "[`date -R`] ${log_tmp}" >> "$LOGFILE"
		else
			logger "${log_tmp}"
		fi
		eval "${SHUTDOWN_CMD}"
	fi
}

NET_TIME=0

USER_TIME=0

while :
do
	do_shutdown_count=0
	do_shutdown_require=0
	DSLEEP=$SLEEP

	NOW=$(date +%s)

	## shutdown based on online computers in ${IPRANGE} network

	if [ -n "${IPRANGE}" ]; then
		do_shutdown_require=$[$do_shutdown_require+1]
		NET_ON_PCS_tmp=`nmap -sP ${IPRANGE} | grep " up " -B 1 | grep scan | awk '{print $5}' | sort`
		NET_ON=`echo "${NET_ON_PCS_tmp}" | wc -w`
		DOMAIN=`hostname -d`
		if [ -n "$DOMAIN" ]; then
			NET_ON_PCS_tmp=${NET_ON_PCS_tmp//$DOMAIN/}
		fi
		if [ "${NET_ON_PCS}" != "${NET_ON_PCS_tmp}" ]; then
			log_tmp="${NET_ON} devices online: `echo ${NET_ON_PCS_tmp} | awk '{printf "%s",$0}'`"
			if [ -n "$LOGFILE" ]; then
				echo "[`date -R`] ${log_tmp}" >> "$LOGFILE"
			else
				logger "${log_tmp}"
			fi
		fi
		NET_ON_PCS=${NET_ON_PCS_tmp}

		# Ignore libvirt VMs
		if [ "${IGNORE_VM}" == "true" ]; then
			VIRSH_CMD=`which virsh 2> /dev/null`
			if [ -n "$VIRSH_CMD" -a -x "$VIRSH_CMD" ]; then
				VMs=`virsh list |grep running|awk '{print $2}'`
				for pc in `echo $NET_ON_PCS_tmp|awk '{printf "%s ",$0}'`
				do
					pc=`echo $pc|awk -F. '{print $1}'`
					if [ -n "$pc" -a -n "`echo $VMs|grep -o "$pc"`" ]; then
						NET_ON=$[$NET_ON-1]
					fi
				done
			fi
		fi

		if [ ${NET_ON} -ne 0 ]; then
			NET_TIME=0
		elif [ ${NET_ON} -eq 0 ] && [ ${NET_TIME} -eq 0 ]; then
			NET_TIME=$(date +%s)
		fi
		if [ ${NET_ON} -eq 0 ] && [ $[$NOW-$NET_TIME] -ge $NET_IDLE ]; then
			do_shutdown_count=$[$do_shutdown_count+1]
			NET_TIME=0
		fi
		TSLEEP=$[$NET_IDLE-$NOW+$NET_TIME]
		if [ $TSLEEP -lt $SLEEP ] && [ $TSLEEP -gt 0 ]; then
			DSLEEP=$TSLEEP
		fi
	fi

	## shutdown based on logged in users

	if [ -n "${USER_IDLE}" ]; then
		do_shutdown_require=$[$do_shutdown_require+1]
		USERS=$(users | wc -w)
		if ! [ ${USERS} -eq 0 ]; then
			USER_TIME=0
		elif [ ${USERS} -eq 0 ] && [ ${USER_TIME} -eq 0 ]; then
			USER_TIME=$(date +%s)
		fi
		if [ ${USERS} -eq 0 ] && [ $[$NOW-$USER_TIME] -ge $USER_IDLE ]; then
			do_shutdown_count=$[$do_shutdown_count+1]
			USER_TIME=0
		fi
		TSLEEP=$[$USER_IDLE-$NOW+$USER_TIME]
		if [ $TSLEEP -lt $SLEEP ] && [ $TSLEEP -gt 0 ]; then
			DSLEEP=$TSLEEP
		fi
	fi

	## shutdown based on time specified in ${FILE}

	if [ -n "${FILE}" ]; then
		do_shutdown_require=$[$do_shutdown_require+1]
		SHUTDOWN=$(cat $FILE)
		if [ -z "$SHUTDOWN" ]; then
			SHUTDOWN=0
		fi
		OFFSET=$[$NOW-$SHUTDOWN]

		if [ $OFFSET -le 10 ] && [ $OFFSET -ge 0 ]; then
			do_shutdown_count=$[$do_shutdown_count+1]
		fi
		TSLEEP=10
		CHECK_FILE=$FILE
		if [ $TSLEEP -lt $SLEEP ] && [ $TSLEEP -gt 0 ]; then
			DSLEEP=$TSLEEP
		fi
	fi

	## perform shutdown
	if [ $do_shutdown_count -eq $do_shutdown_require ]; then
		do_shutdown
	fi

	## sleep
	if [ -n "$CHECK_FILE" ] && [ -f "$CHECK_FILE" ]; then
		inotifywait --quiet --event modify "${CHECK_FILE}" --timeout $DSLEEP
	else
		sleep $DSLEEP
	fi
done
